#ifndef KERNEL_HPP
#define KERNEL_HPP

#include "app.hpp"
#include "request.hpp"
#include "response.hpp"

/**
 * @namespace core
 * Namespace for core application classes and functions.
 */
namespace core {

/**
 * @class Kernel
 * @brief The core class for handling HTTP requests and responses.
 *
 * This class serves as the main entry point for the application, managing
 * the routing and middleware for incoming HTTP requests.
 */
class Kernel {
 public:
  /**
   * @brief Constructor that accepts an instance of the App class.
   * Initializes a new instance of the Kernel class.
   *
   * @param app An instance of the App class.
   */
  Kernel(const App &app);

  /**
   * @brief Handles an incoming HTTP request.
   *
   * @param request The HTTP request to handle.
   * @return The HTTP response generated by the request handler.
   */
  http::Response handleRequest(const http::Request &request);

 private:
  const App &app;  ///< Reference to the App instance.
};

}  // namespace core

#endif  // KERNEL_HPP
