name: Build for Test

on:
  push:
  pull_request:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install CMake
      run: |
        pip install cmake

    - name: Set up dependencies
      run: |
        if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
          sudo apt-get update
          sudo apt-get install -y sqlite3 libsqlite3-dev
        elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
          brew install sqlite3
        elif [[ "${{ matrix.os }}" == "windows-latest" ]]; then
          choco install sqlite
        fi

    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/build-test

    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}/build-test
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Build
      working-directory: ${{github.workspace}}/build-test
      shell: bash
      run: cmake --build . --config $BUILD_TYPE

    - name: Test
      working-directory: ${{github.workspace}}/build-test
      shell: bash
      run: ctest -j6 -C $BUILD_TYPE -T test --output-on-failure
